#
# scattering.py
#
# Scattering class in this script is a usuful class to analyze results obtained
# with Alamode. This class reads .result and .self_isotope files and calculate
# scattering rates, lifetime, cumulative thermal conductivity, etc.
#
# Copyright (c) 2022 Masato Ohnishi
#
# This file is distributed under the terms of the MIT license.
# Please see the file 'LICENCE.txt' in the root directory
# or http://opensource.org/licenses/mit-license.php for information.
#
import os, sys
import os.path
import numpy as np
import pandas as pd

import auto_kappa.units as units
from auto_kappa.io.result import Result
from auto_kappa.io.analyzer import get_average_at_degenerate_point, get_kmode
import matplotlib.pyplot as plt

import logging
logger = logging.getLogger(__name__)

class Scattering():
    """
    Hot To Use
    ------------
    >>> scat = Scattering(options.fresult, 
    ...                   isotope=file_isotope, 
    ...                   temperature=options.T,
    ...                   grain_size=size) 
    >>>
    >>> scat.set_total_scattering_rate()
    >>> print(scat.kappa)
    >>> 
    >>> 
    >>> size = 1000   # nm
    >>> scat.change_grain_size(size)
    >>> 
    >>> T = 100.
    >>> scat.change_temperature(T)
    """
    def __init__(self, file_result: None, temperature=300., file_isotope=None,
                 grain_size=None, verbose=0):
        """
        Parameters
        ----------
        file_result : string
            .result file generated by ALAMODE (ph-ph scattering data)
        
        file_isotope : string
            .self_isotope file generated by ALAMODE (isotope scattering)
        
        grain_size : float
            grain size (nm)
        
        Attributes
        -----------
        scattering_rates[keys]
        
        """
        self.verbose = verbose

        if file_result is None:
            logger.error(" Error: file_result must be given.")
            sys.exit()
        
        self.result = Result(filename=file_result)
        
        ### properties
        self._averaged_velocities = None
        self._mfp = None
        
        ###
        self.scattering_rates = {}
        
        # -- for ph-ph scattering
        self.scattering_rates['phph'] = None
        self._temperature = temperature
        
        # -- for isotope scattering
        self.file_isotope = file_isotope
        self.scattering_rates['isotope'] = None
        
        # -- for boundary scattering
        self.scattering_rates['boundary'] = None
        self._size  = grain_size
        
        self._total_scattering_rate = None
        """
        .lifetime : ndarray, float, shape=(nk,nb)
            lifetime [ps]
        .kappa : ndarray, float, shape=(3,3)
            thermal conductivity k(xx, xy, xz, ...)
        .kmode : ndarray, float, shape=(nk,nb)
            modal thermal conductivity
        """
        self._lifetime = None
        self._kappa = None
        self._kmode = None
        
        ### ph-ph scattering, T-dependent
        self.set_scattering_rate_phph()
        
        ### T-independent
        if self.file_isotope is not None:
            self.set_scattering_rate_isotope()
        
        ### T-independent
        if self.size is not None:
            self.set_scattering_rate_boundary(size=self.size)
    
    @property
    def temperatures(self):
        try:
            return self.result['temperatures']
        except (AttributeError, KeyError, TypeError):
            return None
    
    @property
    def kpoints(self):
        return self.result['kpoints']

    @property
    def frequencies(self):
        return self.result['frequencies']
    
    @property
    def averaged_velocities(self):
        if self._averaged_velocities is None:
            self.set_averaged_velocities()
        return self._averaged_velocities
    
    def set_averaged_velocities(self):
        
        nk = self.result['nk']
        nb = self.result['nbands']
        vg_ave = np.zeros((nk, nb))
        for ik in range(nk):
            for ib in range(nb):
                vg_multi = self.result['velocities'][ik][ib]
                for vg_each in vg_multi:
                    vg_ave[ik,ib] += np.linalg.norm(vg_each) / len(vg_multi)
        self._averaged_velocities = vg_ave
    
    @property
    def mfp(self):
        if self._mfp is None:
            self.set_mfp()
        return self._mfp
    
    def set_mfp(self):
        ## units: velo (m/s), lifetime (ps), mfp (nm)
        self._mfp = self.averaged_velocities * self.lifetime * 0.001
    
    @property
    def temperature(self):
        return self._temperature
    
    @property
    def size(self):
        return self._size
    
    @property
    def total_scattering_rate(self):
        if self._total_scattering_rate is None:
            self.set_total_scattering_rate()
        return self._total_scattering_rate
    
    def set_total_scattering_rate(self):
        if (self.file_isotope is not None and
            self.scattering_rates['isotope'] is None):
            self.set_scattering_rate_isotope()

        if (self.size is not None and
            self.scattering_rates['boundary'] is None):
            self.set_scattering_rate_boundary()
        
        ##
        self._total_scattering_rate = np.zeros_like(
            self.scattering_rates['phph'])
        
        msg = " ### Calculate total scattering rate"
        for key in self.scattering_rates:
            if self.scattering_rates[key] is not None:
                msg += "  * %s\n" % key
                self._total_scattering_rate += self.scattering_rates[key]
        msg += "\n"
        if self.verbose > 0:
            logger.info(msg)
        
        self.set_lifetime()
        self.set_kmode()
    
    @property
    def lifetime(self):
        """ Lifetime with the unit of pico second (ps) """
        if self._lifetime is None:
            self.set_lifetime()
        return self._lifetime
    
    def set_lifetime(self):
        """calculate lifetime and thermal conductivity
        """
        lifetime = convert_scatrate2lifetime(
                self.total_scattering_rate)  # ps
        self._lifetime = get_average_at_degenerate_point(
                self.result['frequencies'], lifetime)
        
    @property
    def kmode(self):
        if self._kmode is None:
            self.set_kmode()
        return self._kmode

    @property
    def kappa(self):
        if self._kappa is None:
            self.set_kmode()
        return self._kappa
    
    def set_kmode(self, verbose=True):
        """calculate model thermal conductivity
        """
        self._kappa, self._kmode = \
            get_kmode(self.result['volume'],
                      self.temperature,
                      self.result['frequencies'],
                      self.result['multiplicity'],
                      self.result['velocities'],
                      self.lifetime,
                      verbose=verbose)
    
    def get_cumulative_kappa(self, temperature=300., grain_size=None,
            wrt='frequency', nbins=200, xscale='linear'):
        """ Return cumulative kappa w.r.t the given property, frequency or MFP.

        Args
        -------
        wft : string
            "frequency" or "mfp"
        
        Return
        ---------
        df : DataFrame
        df['xdat'] : array, shape=(nk*nb)
            values of the given property, frequency or MFP
        df['kspec'] : array,
            cumulative kappa
        df['kcumu'] : array,
            spectral kappa
        """
        ## set grain size
        if self.size != grain_size:
            self._size = grain_size
            self.change_grain_size(grain_size)
        
        ## set temperature
        if abs(self.temperature - temperature) > 0.1:
            self.change_temperature(temperature)
        
        ### get non-directional cumulative kappa
        nk = self.result['nk']
        nbands = self.result['nbands']
        frequencies = self.result['frequencies']
        
        if 'freq' in wrt.lower():
            xorig = frequencies.reshape(nk*nbands)  ## 1/cm
        else:
            xorig = self.mfp.reshape(nk*nbands)     ## nm

        kmodes = np.zeros_like(frequencies)
        for ik in range(nk):
            for ib in range(nbands):
                kmodes[ik,ib] = np.average(np.diagonal(self.kmode[ik,ib]))
        
        yorig = kmodes.reshape(nk*nbands)
        
        ### (frequency or MFP) vs cumulative kappa
        if xscale == 'log':
            
            idx = np.where(xorig>1e-5)[0]
            xmod = xorig[idx]
            ymod = yorig[idx]
            
            isort = np.argsort(xmod)
            
            ### adjust xmin
            xmin = xmod[isort[5]]
            if wrt == 'mfp':
                mm = max(5., np.min(xmod))
                if mm < np.max(xmod):
                    xmin = mm
            
            xmin_log = np.log10(xmin)
            xmax_log = np.log10(np.max(xmod))
            xbins = np.logspace(xmin_log, xmax_log, nbins+1)
            
        else:
            isort = np.argsort(xorig)
            #xmin = xorig[isort[3]]
            xmin = 0.
            xmax = np.max(xorig)
            xbins = np.linspace(xmin, xmax, nbins+1)
        
        xbins[0] = np.min(xorig) - 1e-3
        ybins = np.zeros_like(xbins)
        cats = pd.cut(xorig, xbins)
        idx = cats.codes
        for i, x in enumerate(xorig):
            ybins[idx[i]] += yorig[i]
        
        ###
        df = pd.DataFrame()
        df['xdat'] = xbins
        df['kcumu'] = ybins.cumsum()
        df['kspec'] = ybins
        return df
    
    def get_kmin_cahill(self, bvec, temperature):
        """
        Args
        -------
        bvec : shape=(3,3), reciprocal vectors
        
        Return
        ----------
        kappa : shape=()
        kmode : shape=()

        Example
        -----------
        >>> 
        >>> bvec = atoms.cell.get_reciprocal()
        >>> kmin, kmode = scat.get_kmin_cahill(bvec, T)
        >>> 
        """
        from .analyzer import get_heat_capacity
        
        nk = len(self.result['frequencies'])
        nb = len(self.result['frequencies'][0])
        
        ## wavevectors: [1/A], shape=(nk,3)
        wavevectors = np.dot(self.result['kpoints'], bvec)
        
        ## norm of wavevectors
        wave_norm = np.zeros(nk)
        for ik in range(nk):
            wave_norm[ik] = np.linalg.norm(wavevectors[ik])   # 1/A
        
        ## wavelength: shape=(nk)
        wavelengths = np.zeros(nk)
        idx1 = np.where(abs(wave_norm) >= 1e-7)
        wavelengths[idx1] = 0.1 / wave_norm[idx1]   # nm
        
        ## with minimum MFP
        kmode = np.zeros((nk,nb,3))
        multiplicity = self.result['multiplicity']
        for ik in range(nk):
            wl = wavelengths[ik] * 1e-9    # m
            multi = multiplicity[ik]
            for ib in range(nb):
                vg = np.zeros(3)
                for im in range(multi):
                    vg += abs(self.result['velocities'][ik,ib,im] / multi)
                ##
                if self.result['frequencies'][ik,ib] < 0.:
                    kmode[ik,ib] = np.zeros(3)
                else:
                    Cph = get_heat_capacity(
                            self.result['frequencies'][ik,ib], 
                            temperature)  # J/K
                    
                    ## ver.1
                    kmode[ik,ib] = vg * Cph * wl*0.5 * multi    # W*m^2/K
                    ## ver.2
                    #mfp = vg * self.lifetime[ik,ib] * 1e-12
                    #kmode[ik,ib] = vg * Cph * mfp * multi
                    # W*m^2/K
        
        ## modal kappa [W/m/K]
        volume = self.result['volume']
        kmode *= (1./volume/(units.BohrToM**3)/ float(np.sum(multiplicity)))
        
        ## total kappa
        kappa = np.zeros(3)
        for j in range(3):
            kappa[j] = np.sum(kmode[:,:,j])
        
        return kappa, kmode
    
    #def get_squared_velocities(self):
    #    """
    #    Return
    #    -----------
    #    v2s : shape=(nk,nb,3,3), |vg|^2
    #    """
    #    ## get v2tensor
    #    nk = len(self.result['frequencies'])
    #    nb = len(self.result['frequencies'][0])
    #    
    #    v2s = np.zeros((nk,nb,3,3))
    #    for ik in range(nk):
    #        for ib in range(nb):
    #            v2tensor = np.zeros((3,3))
    #            for im in range(self.result['multiplicity'][ik]):
    #                #        vaves += 
    #                v2tensor += (
    #                        self.result['velocities'][ik][ib][im] *
    #                        self.result['velocities'][ik][ib][im].reshape(3,1)
    #                        )
    #            ##
    #            v2s[ik,ib,:,:] = v2tensor
    #    return v2s
    
    def change_temperature(self, temperature):
        """set temperature and update properties
        """
        idx = np.argmin(abs(self.result['temperatures'] - temperature))
        
        self._temperature = self.result['temperatures'][idx]
        
        if abs(self.temperature - temperature) > 0.1:
            msg = "\n NOTE: target temperature is adjusted from %.1f K to "\
                    "%.1f K.\n" % (temperature, self.temperature)
            logger.info(msg)
            sys.exit()
        
        self.set_scattering_rate_phph()
        self.set_total_scattering_rate()
        self.set_kmode()
    
    def change_grain_size(self, size):
        self._size = size
        self.set_scattering_rate_boundary()
        self.set_total_scattering_rate()
        self.set_kmode()

    def set_scattering_rate_phph(self):
        ## , smooth_scattering_rate=True, tol_gap=10.
        """ Set scattering rate due to ph-ph scattering.
        
        Args
        -------
        smooth_scattering_rate : bool
            if True, replace too small scattering rate to average 
            value for modes above the band gap.
        tol_gap : float
            if difference of frequencies  is larger than 
            tol_gap [kayser], the difference is regarded as gap.
        """
        itarget = np.argmin(abs(self.result['temperatures'] - self.temperature))
        
        ## 1/ps
        self.scattering_rates['phph'] = convert_gamma2scatrate(
            self.result['gammas'][itarget,:,:])
        
        # if self.has_gap(tol_gap=10.0) != False:
        #     logger.info(f'\n Note: Band gap exists. '
        #                 f'({self.has_gap(tol_gap=10.0)} 1/cm)')
        
        # if smooth_scattering_rate:
        #     self._smooth_scattering_rate(tol_gap=tol_gap)
    
    def has_gap(self, tol_gap=None):
        """ Check if there is a band gap or not.
        
        Return
        --------
        fmin : float
            minimum frequency above the band gap
        """
        ordered_freqs = np.sort(self.result['frequencies'][:,3:].flatten())
        diff_freqs = np.diff(ordered_freqs)
        idx_gap = np.where(diff_freqs > tol_gap)[0]
        if len(idx_gap) == 0:
            return False
        else:
            fmin = ordered_freqs[idx_gap[0]+1]
            return fmin
    
    #
    # To Do:
    # When the scattering rate of some modes is too small, four-phonon scattering should be considred.
    # Currently, the presence of a band gap is checked.
    #
    # def _smooth_scattering_rate(self, tol_gap=None, tol_scatrate=1e-10, tol_kappa=1e-3):
    #     """ Replace too small scattering rate to average value 
    #     for modes above the band gap.
        
    #     Args
    #     -------
    #     tol_gap : float
    #         if difference of frequencies is larger than tol_gap, 
    #         the difference is regarded as gap.
    #     """
    #     ## Minimum frequency above the band gap
    #     fmin = self.has_gap(tol_gap=tol_gap)
    #     if fmin == False:
    #         return None
        
    #     from auto_kappa.alamode.analyzer.analyzer import get_heat_capacity
        
    #     ## Replace too small scattering rate to average value
    #     nk, nb = self.scattering_rates['phph'].shape
    #     for ik in range(nk):
    #         for ib in range(nb):
                
    #             freq = self.result['frequencies'][ik,ib]  # 1/cm
    #             if freq < fmin:
    #                 continue
                
    #             rscat = self.scattering_rates['phph'][ik,ib]  # 1/ps
                
    #             if rscat < tol_scatrate:
    #                 self.scattering_rates['phph'][ik,ib] = np.nan
                
    #             tau = 1./rscat  # ps
    #             vg = self.averaged_velocities[ik,ib]  # m/s
    #             mfp = vg * 0.001 / rscat  # nm
    #             Cph = get_heat_capacity(freq, self.temperature)   # J/K
    #             kappa = Cph * vg * mfp * 1e-9  # m^3 * W/m/K
    #             kappa /= self.result['volume'] * units.BohrToM**3  # W/m/K
                
    #             if mfp > 1000. and kappa > tol_kappa:
    #                 print(ik, ib, 'freq= %.3f 1/cm, tau= %.3e ps, MFP= %.3f nm, k= %.3f' % (
    #                     freq, tau, mfp, kappa))
    #                 self.scattering_rates['phph'][ik,ib] = np.nan
    
    def set_scattering_rate_isotope(self):
        from auto_kappa.io.isotope import Isotope
        if os.path.exists(self.file_isotope) == False:
            logger.warning(" %s does not exist." % self.file_isotope)
        else:
            iso = Isotope(filename=self.file_isotope)
            ## 1/ps
            self.scattering_rates['isotope'] = convert_gamma2scatrate(iso.gammas)
    
    def set_scattering_rate_boundary(self, size=None):
        """ Scattering rates due to grain boundaries are calculated with
        2*|v|/L, where v and L are group velocities and grain size. 
        """
        if size is None:
            size = self.size
        else:
            self._size = size
        
        if self.size is None or self.size <= 0.:
            self.scattering_rates['boundary'] = None
            return None
         
        ## rate [1/ps]
        self.scattering_rates['boundary'] = 1e-3 * 2. * self.averaged_velocities / size
    
    def plot_lifetime(self, ax, temperature=300, label=None,
                      marker='o', ms=1.3, lw=0.3, color='blue'):
        """ Plot phonon lifetime as a function of frequency.
        """
        self.change_temperature(temperature)
        
        nk = self.result['nk']
        nb = self.result['nbands']
        
        xorig = self.result['frequencies'].reshape(nk*nb)  # 1/cm
        yorig = self.lifetime.reshape(nk*nb)     # ps
        
        _plot_share_for_mode_property(
            ax, xorig, yorig, color=color, marker=marker,
            lw=lw, ms=ms, label=label)

    def plot_scattering_rates(self, ax, ms=1.3, lw=0.3, process=None):
        """ Plot scattering rates for different processes.
        """
        cmap = plt.get_cmap("tab10")
        n1, n2 = self.frequencies.shape
        xorig = self.result['frequencies'].reshape(n1*n2)
        
        markers = ['o', '^', 's', 'd', 'v']
        xlim = [100, -100]
        ylim = [100, -100]
        icol = 0
        for ik, key in enumerate(self.scattering_rates):
            
            if self.scattering_rates[key] is None:
                continue
            
            if key == 'phph':
                try:
                    label = f'{process}({self.temperature:.0f}K)'
                except:
                    label = key
            elif key == "boundary":
                label = f"L={self.size:.0f}nm"
            else:
                label = key
            
            yorig = self.scattering_rates[key].reshape(n1*n2)
            
            xlim_ik, ylim_ik = _plot_share_for_mode_property(
                ax, xorig, yorig, color=cmap(icol), marker=markers[ik%len(markers)],
                lw=lw, ms=ms, label=label)
            
            if xlim_ik is None:
                logger.info(" No valid data for %s", label)
                continue
            icol += 1
            
            xlim[0] = min(xlim[0], xlim_ik[0])
            xlim[1] = max(xlim[1], xlim_ik[1])
            ylim[0] = min(ylim[0], ylim_ik[0])
            ylim[1] = max(ylim[1], ylim_ik[1])
        
        ax.set_xlim(_get_log_range(xlim[0], xlim[1], space=0.05))
        ax.set_ylim(_get_log_range(ylim[0], ylim[1], space=0.05))
        

def _plot_share_for_mode_property(ax, xorig, yorig, color='black', marker='o', lw=0.5, ms=2.3,
                                  alpha=1.0, label=None, xtol=1e-7, ytol=1e-5):

    idx_pos = np.where((xorig > xtol) & (yorig > ytol))[0]
    if len(idx_pos) == 0:
        return None, None
    
    xdat, ydat = xorig[idx_pos], yorig[idx_pos]
    ax.plot(xdat, ydat, linestyle='None', mfc='none',
            marker=marker, ms=ms, mew=lw, mec=color, alpha=alpha,
            label=label)
    
    ### Do not show too small (and too large) values for setting axis range
    def _get_valid_range(values, num_low=5):
        isort = np.argsort(values)
        v0 = np.min(values[isort][num_low:])
        v1 = np.max(values[isort])
        return v0, v1
    
    xlim = [np.min(xdat), np.max(xdat)]
    ylim = _get_valid_range(ydat)
    ax.set_xlim(_get_log_range(xlim[0], xlim[1], space=0.01))
    ax.set_ylim(_get_log_range(ylim[0], ylim[1], space=0.01))
    return xlim, ylim

def _get_log_range(vmin, vmax, space=0.05):
    if vmin <= 0 or vmax <= 0:
        return [vmin, vmax]
    vmin_log = np.log10(vmin)
    vmax_log = np.log10(vmax)
    dv_log = vmax_log - vmin_log
    v0_log = vmin_log - dv_log * space
    v1_log = vmax_log + dv_log * space
    v0 = np.power(10, v0_log)
    v1 = np.power(10, v1_log)
    return [v0, v1]

###
def convert_gamma2scatrate(gammas):
    """
    Unit of gamma : Kayser [1/cm]
    Unit of scattering rate : [1/ps]
    """
    return 2. * gammas * units.AlmCmToHz * 1e-12

def convert_scatrate2lifetime(rscat, epsilon=1e-10):
    """
    Unit of scattering rate : [1/ps]
    Unit of lifetime : [ps]
    """
    ### old version
    # rscat_tmp = np.where(rscat<epsilon, 1.0, rscat)
    # lifetime = np.where(rscat<epsilon, 0.0, 1./rscat_tmp)
    
    ### modified version
    with np.errstate(divide='ignore', invalid='ignore'):
        lifetime = np.where((np.isnan(rscat)) | (rscat < epsilon), 0.0, 1./rscat)
    
    return lifetime
